config/routes.rb
RubyRails4Sample::Application.routes.draw do

  devise_for :models
  get "home/index"
  root :to => "home#index"
  get 'ganar/' => 'ganar#index'
  post 'ganar/guardar' => 'ganar#guardar'
  get 'ganar/informe_persona' => 'ganar#informe_persona'

  get 'organizacion/plan_trabajo' => 'organizacion#plan_trabajo'
  get 'comunicar/index' => 'comunicar#index'

  get 'patrimonio/equipos' => 'patrimonio#equipo'
  get 'patrimonio/ambiente' => 'patrimonio#ambiente'
  get 'patrimonio/asignacionambiente' => 'patrimonio#asignacionambiente'
  get 'patrimonio/material' => 'patrimonio#material'
  get 'secretaria/evento' => 'secretaria#evento'

  get 'planilla/index' => 'planilla#index'
  get 'pago/index' => 'pago#index'
  

  

end

app/models/actividad.rb
class Actividad < ActiveRecord::Base
	belongs_to	:plantrabajo
end

app/models/ambiente.rb
class Ambiente < ActiveRecord::Base
	has_many	:asignacionrecurso
end

app/models/asignacionrecurso.rb
class Asignacionrecurso < ActiveRecord::Base
	has_many	:detallematerial, foregin_key: "int_asignacionrecurso_id"
	belongs_to	:ambiente
end

app/models/detalle_sms.rb
class DetalleSms < ActiveRecord::Base
	belongs_to	:sms
	belongs_to	:persona
end

app/models/detallematerial.rb
class Detallematerial < ActiveRecord::Base
	belongs_to	:material
	belongs_to	:asignacionrecurso
end

app/models/evento.rb
class Evento < ActiveRecord::Base
	has_many	:listacontacto
end

app/models/listacontacto.rb
class Listacontacto < ActiveRecord::Base
	belongs_to	:evento
end

app/models/lugar.rb
class Lugar < ActiveRecord::Base
	has_many	:persona
end

app/models/material.rb
class Material < ActiveRecord::Base
	has_many :detallematerial, foreign_key: "int_material_id"
end

app/models/model.rb
class Model < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/persona.rb
class Persona < ActiveRecord::Base
	has_many	:plantrabajo
	has_many	:detalle_sms
	belongs_to	:lugar
end

app/models/plantrabajo.rb
class Plantrabajo < ActiveRecord::Base
	has_many	:actividad
	belongs_to	:persona
end

app/models/sms.rb
class Sms < ActiveRecord::Base
	has_many	:detalle_sms
end

app/models/ubigeo.rb
class Ubigeo < ActiveRecord::Base
end

app/controllers/ganar_controller.rb
class GanarController < ApplicationController
	def index
		@title = ''
	end
	def informe_persona
		@title = "Informe"
	end

	def guardar
		
	end
end

app/helpers/comunicar_helper.rb
module ComunicarHelper
end

app/helpers/ganar_helper.rb
module GanarHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/pago_helper.rb
module PagoHelper
end

app/helpers/patrimonio_helper.rb
module PatrimonioHelper
end

app/helpers/planilla_helper.rb
module PlanillaHelper
end

app/helpers/secretaria_helper.rb
module SecretariaHelper
end

app/views/ganar/index.html.haml
.widget.widget-nopad
  .widget-header
    %i.icon-search
    %h3 Buscar
    %a.btn{"data-toggle" => "modal", href: "#ModalRegistrar", style: "float: right; margin: 6px;"}
      %i.icon-plus{style: "margin:0; "}
  .widget-content
    .widget.big-stats-container
      .widget-content
        %br/
        = form_tag( ganar_guardar_path,{:method=>'post',:class=>'form-horizontal'}) do
          %fieldset
            .control-group
              %label.control-label{for: "filtro"} Filtro
              .controls
                %input#filtro.span2{style: "margin-right:20px;", type: "text"}/
                %select#tipofiltro.span2{style: "margin-right:20px;"}
                  %option{value: "1"} Nombre
                  %option{value: "2"} Apellido
                %button.btn.btn-primary{type: "submit"} Buscar
              / /controls
            / /control-group
        %table.table.table-striped.table-bordered
          %thead
            %tr
              %th Nombre y Apellido
              %th Teléfono
              %th Celular
              %th Fecha de Conversión
              %th.td-actions
          %tbody
            %tr
              %td Fresh Web Development Resources
              %td http://www.egrappler.com/
              %td Fresh Web Development Resources
              %td http://www.egrappler.com/
              %td.td-actions
                %a.btn.btn-success{href: "#"}
                  %i.icon-edit
                  Editar
                %a.btn.btn-info{href: ganar_informe_persona_path}
                  %i.icon-file-alt
                  Informe
  / Modal
  #ModalRegistrar.modal.hide.fade{"aria-hidden" => "true", "aria-labelledby" => "myModalLabel", role: "dialog", tabindex: "-1"}
    .modal-header
      %button.close{"aria-hidden" => "true", "data-dismiss" => "modal", type: "button"} ×
      %h3#myModalLabel Registrar
    .modal-body
      .tabbable
        %ul.nav.nav-tabs
          %li.active
            %a{"data-toggle" => "tab", href: "#personales"} Datos Personales
          %li
            %a{"data-toggle" => "tab", href: "#directorio"} Datos Directorio
          %li
            %a{"data-toggle" => "tab", href: "#redessociales"} Datos Redes Sociales
          %li
            %a{"data-toggle" => "tab", href: "#finales"} Datos Finales
        %br/
        %form#registrarGanado
          .tab-content
            #personales.tab-pane.active
              .span3
                .form-horizontal
                  %fieldset
                    .control-group
                      %label.control-label{for: "nombre", style: "width:auto;"} Nombre
                      .controls{style: "margin-left: 90px;"}
                        %input#nombre.span2{name: "nombre", type: "text"}/
                      / /controls
                    / /control-group
                    .control-group
                      %label.control-label{for: "estadocivil", style: "width:auto;"} Estado Civil
                      .controls{style: "margin-left: 90px;"}
                        %select#estadocivil.span2{name: "estadocivil"}
                          %option{value: "1"} Soltero
                          %option{value: "2"} Casado
                      / /controls
                    / /control-group
                    .control-group
                      %label.control-label{for: "dni", style: "width:auto;"} D.N.I.
                      .controls{style: "margin-left: 90px;"}
                        %input#dni.span2{name: "dni", type: "text"}/
                      / /controls
                    / /control-group
              / /span3
              .span3
                .form-horizontal
                  %fieldset
                    .control-group
                      %label.control-label{for: "apellido", style: "width:auto;"} Apellido
                      .controls{style: "margin-left: 90px;"}
                        %input#apellido.span2{name: "apellido", type: "text"}/
                      / /controls
                    / /control-group
                    .control-group
                      %label.control-label{for: "sexo", style: "width:auto;"} Sexo
                      .controls{style: "margin-left: 90px;"}
                        %select#sexo.span2{name: "sexo"}
                          %option{value: "1"} Masculino
                          %option{value: "2"} Femenino
                      / /controls
                    / /control-group
                    .control-group
                      %label.control-label{for: "ocupacion", style: "width:auto;"} Ocupación
                      .controls{style: "margin-left: 90px;"}
                        %input#ocupacion.span2{name: "ocupacion", type: "text"}/
                      / /controls
                    / /control-group
              / /span3
              .span3
                .form-horizontal
                  %fieldset
                    .control-group
                      %label.control-label{for: "edad", style: "width:auto;"} Edad
                      .controls{style: "margin-left: 90px;"}
                        %input#edad.span2{name: "edad", type: "text"}/
                      / /controls
                    / /control-group
                    .control-group
                      %label.control-label{for: "fec_nac", style: "width:auto;"} Fec. Nac.
                      .controls{style: "margin-left: 90px;"}
                        %input#fec_nac.span2.datepicker{name: "fec_nac", type: "text"}/
                      / /controls
                    / /control-group
                    .control-group
                      %label.control-label{for: "profesion", style: "width:auto;"} Profesión
                      .controls{style: "margin-left: 90px;"}
                        %input#profesion.span2{name: "profesion", type: "text"}/
                      / /controls
                    / /control-group
              / /span3
            / /FIN DATOS PERSONALES
            #directorio.tab-pane
              .form-horizontal
                %fieldset
                  .control-group
                    %label.control-label{for: "telefono"} Teléfono
                    .controls
                      %input#telefono.span2{name: "telefono", style: "margin-right:20px;", type: "text"}/
                      %label{style: "display: inline; margin-right:20px;"} Tipo
                      %select#sexo.span2{name: "sexo"}
                        %option{value: "1"} Casa
                        %option{value: "2"} Móvil
                        %option{value: "3"} Trabajo
                    / /controls
                  / /control-group
                %table.table.table-striped.table-bordered
                  %thead
                    %tr
                      %th Teléfono
                      %th Tipo
                      %th.td-actions
                  %tbody
                    %tr
                      %td 147258639
                      %td Móvil
                      %td.td-actions
                        %a.btn.btn-danger{href: "#"}
                          %i.icon-remove
                          Eliminar
                = field_set_tag do
                  = render 'layouts/ubigeo', dist: ''
                  / /controls
                  / /control-group
                  .control-group
                    %label.control-label{for: "direccion"} Dirección
                    .controls
                      %input#direccion.span6{name: "direccion", type: "text"}/
                    / /controls
                  / /control-group
                  .control-group
                    %label.control-label{for: "referencia"} Referencia
                    .controls
                      %input#referencia.span6{name: "referencia", type: "text"}/
                    / /controls
                  / /control-group
                  .control-group
                    %label.control-label{for: "map"} Mapa
                    .controls
                      = render 'layouts/mapa', lat: '-8.112489', lng:'-79.0288469'
                    
                    / /controls
                  / /control-group
            / /FIN DIRECTORIO
            #redessociales.tab-pane
              .form-horizontal
                %fieldset
                  .control-group
                    %label.control-label{for: "email"} Email
                    .controls
                      %input#email.span6{name: "email", type: "text"}/
                    / /controls
                  / /control-group
                .span4
                  .form-horizontal
                    %fieldset
                      .control-group
                        %label.control-label{for: "usuariof"} Usuario Facebook
                        .controls
                          %input#usuariof.span2{name: "usuariof", type: "text"}/
                        / /controls
                      / /control-group
                      .control-group
                        %label.control-label{for: "usuariot"} Usuario Twitter
                        .controls
                          %input#usuariot.span2{name: "usuariot", type: "text"}/
                        / /controls
                      / /control-group
                / /span4
                .span4
                  .form-horizontal
                    %fieldset
                      .control-group
                        %label.control-label{for: "enlacef"} Enlace Facebook
                        .controls
                          %input#enlacef.span2{name: "enlacef", type: "text"}/
                        / /controls
                      / /control-group
                      .control-group
                        %label.control-label{for: "enlacet"} Enlace Twitter
                        .controls
                          %input#enlacet.span2{name: "enlacet", type: "text"}/
                        / /controls
                      / /control-group
                / /span4
            / /FIN REDES SOCIALES
            #finales.tab-pane
              .form-horizontal
                %fieldset
                  .control-group
                    %label.control-label{for: "red"} Red
                    .controls
                      %select#red.span2{name: "red", style: "margin-right:20px;"}
                        %option{value: "1"} Casa
                        %option{value: "2"} Móvil
                        %option{value: "3"} Trabajo
                      %label{style: "display: inline; margin-right:20px;"} Lugar
                      %select#red.span2{name: "red", style: "margin-right:20px;"}
                        %option{value: "1"} Casa
                        %option{value: "2"} Móvil
                        %option{value: "3"} Trabajo
                      %label{style: "display: inline; margin-right:20px;"} Fec. Conversión
                      %input#fec_conv.span2.datepicker{name: "fec_conv", style: "margin-right:20px;", type: "text"}/
                    / /controls
                  / /control-group
                  .control-group
                    %label.control-label Día Visita
                    .controls
                      %input#dia_visita.span2{name: "dia_visita", style: "margin-right:20px;", type: "text"}/
                      %label{style: "display: inline; margin-right:20px;"} Hora Visita
                      %input#hora_visita.span2{name: "hora_visita", style: "margin-right:20px;", type: "text"}/
                    / /controls
                  / /control-group
                  .control-group
                    %label.control-label{for: "invitadopor"} Invitado por
                    .controls
                      %input#invitadopor.span4{name: "invitadopor", type: "text"}/
                    / /controls
                  / /control-group
                  .control-group
                    %label.control-label{for: "motivo_oracion"} Mot. Oración
                    .controls
                      %textarea#motivo_oracion.span4{name: "motivo_oracion"}
                    / /controls
                  / /control-group
            / /FIN DATOS DE RED
    .modal-footer
      %button.btn{"aria-hidden" => "true", "data-dismiss" => "modal"} Cancelar
      %button.btn.btn-primary{type: "submit"} Guardar
  / Modal

app/views/ganar/informe_persona.html.haml
.widget.widget-nopad
  .widget-header
    %h3 Informe
    %a.btn{"data-toggle" => "modal", href: "#", style: "float: right; margin: 6px;"}
      %i.icon-envelope-alt{style: "margin:0; "}
      Correo
    %a.btn{"data-toggle" => "modal", href: "#", style: "float: right; margin: 6px;"}
      %i.icon-file-text-alt{style: "margin:0; "}
      PDF
    %a.btn{"data-toggle" => "modal", href: "#", style: "float: right; margin: 6px;"}
      %i.icon-file-text-alt{style: "margin:0; "}
      Excel
    %a.btn{href: ganar_path, style: "float: right; margin: 6px;"}
      %i.icon-arrow-left{style: "margin:0; "}
      Volver
  .widget-content
    .widget.big-stats-container
      .widget-content
        %br/
        %h3{style: "margin-left:30px;"} Datos Personales
        %br/
        .span4
          .form-horizontal
            %fieldset
              .control-group
                %label.control-label{for: "nombre", style: "width:auto;"} Nombre
                .controls{style: "margin-left: 90px;"}
                  %label{style: "padding-top: 5px;"} Claudia María
                / /controls
              / /control-group
              .control-group
                %label.control-label{for: "estadocivil", style: "width:auto;"} Estado Civil
                .controls{style: "margin-left: 90px;"}
                  %label{style: "padding-top: 5px;"} Soltero
                / /controls
              / /control-group
              .control-group
                %label.control-label{for: "dni", style: "width:auto;"} D.N.I.
                .controls{style: "margin-left: 90px;"}
                  %label{style: "padding-top: 5px;"} 12345678
                / /controls
              / /control-group
        / /span4
        .span4
          .form-horizontal
            %fieldset
              .control-group
                %label.control-label{for: "apellido", style: "width:auto;"} Apellido
                .controls{style: "margin-left: 90px;"}
                  %label{style: "padding-top: 5px;"} Valdivieso Castillo
                / /controls
              / /control-group
              .control-group
                %label.control-label{for: "sexo", style: "width:auto;"} Sexo
                .controls{style: "margin-left: 90px;"}
                  %label{style: "padding-top: 5px;"} Femenino
                / /controls
              / /control-group
              .control-group
                %label.control-label{for: "ocupacion", style: "width:auto;"} Ocupación
                .controls{style: "margin-left: 90px;"}
                  %label{style: "padding-top: 5px;"} Developer
                / /controls
              / /control-group
        / /span4
        .span4
          .form-horizontal
            %fieldset
              .control-group
                %label.control-label{for: "edad", style: "width:auto;"} Edad
                .controls{style: "margin-left: 90px;"}
                  %label{style: "padding-top: 5px;"} 23
                / /controls
              / /control-group
              .control-group
                %label.control-label{for: "fec_nac", style: "width:auto;"} Fec. Nac.
                .controls{style: "margin-left: 90px;"}
                  %label{style: "padding-top: 5px;"} 26-04-1990
                / /controls
              / /control-group
              .control-group
                %label.control-label{for: "profesion", style: "width:auto;"} Profesión
                .controls{style: "margin-left: 90px;"}
                  %label{style: "padding-top: 5px;"} Ing. Informática
                / /controls
              / /control-group
        / /span4
        %hr{style: "display:block;"}/
        %br/
        %h3{style: "margin-left:30px;"} Datos Directorio
        %br/
        %table.table.table-striped.table-bordered
          %thead
            %tr
              %th Teléfono
              %th Tipo
          %tbody
            %tr
              %td 147258639
              %td Móvil
        %hr/
        %br/
        .span4
          .form-horizontal
            %fieldset
              .control-group
                %label.control-label{for: "nombre", style: "width:auto;"} Depart.
                .controls{style: "margin-left: 90px;"}
                  %label{style: "padding-top: 5px;"} La Libertad
                / /controls
              / /control-group
              .control-group
                %label.control-label{for: "nombre", style: "width:auto;"} Dirección
                .controls{style: "margin-left: 90px;"}
                  %label{style: "padding-top: 5px;"} Mi Casa 123
                / /controls
              / /control-group
        / /span4
        .span4
          .form-horizontal
            %fieldset
              .control-group
                %label.control-label{for: "nombre", style: "width:auto;"} Provincia
                .controls{style: "margin-left: 90px;"}
                  %label{style: "padding-top: 5px;"} Trujillo
                / /controls
              / /control-group
        / /span4
        .span4
          .form-horizontal
            %fieldset
              .control-group
                %label.control-label{for: "nombre", style: "width:auto;"} Distrito
                .controls{style: "margin-left: 90px;"}
                  %label{style: "padding-top: 5px;"} Victor Larco
                / /controls
              / /control-group
        / /span4
        %br/
        %div{style: "clear:both;"}
        .span6{style: "margin:0 auto;"}
          %h1 MAPA
        %div{style: "clear:both;"}
        %br/
        %h3{style: "margin-left:30px;"} Datos Redes Sociales
        %br/
        .span6
          .form-horizontal
            %fieldset
              .control-group
                %label.control-label{for: "nombre", style: "width:auto;"} Email
                .controls{style: "margin-left: 90px;"}
                  %label{style: "padding-top: 5px;"} clindy.26@gmail.com
                / /controls
              / /control-group
              .control-group
                %label.control-label{for: "nombre", style: "width:auto;"} Facebook
                .controls{style: "margin-left: 90px;"}
                  %label{style: "padding-top: 5px;"} Claudia Valdivieso Castillo
                / /controls
              / /control-group
              .control-group
                %label.control-label{for: "nombre", style: "width:auto;"} Twitter
                .controls{style: "margin-left: 90px;"}
                  %label{style: "padding-top: 5px;"} lavaldi_
                / /controls
              / /control-group
        / /span6
        .span6
          .form-horizontal
            %fieldset
              .control-group
                %label.control-label{for: "nombre", style: "width:auto;"}
                .controls{style: "margin-left: 90px;"}
                  %label{style: "padding-top: 5px;"} .
                / /controls
              / /control-group
              .control-group
                %label.control-label{for: "nombre", style: "width:auto;"} Facebook
                .controls{style: "margin-left: 90px;"}
                  %label{style: "padding-top: 5px;"} https://www.facebook.com/ClaudiaValdiviesoCastillo
                / /controls
              / /control-group
              .control-group
                %label.control-label{for: "nombre", style: "width:auto;"} Twitter
                .controls{style: "margin-left: 90px;"}
                  %label{style: "padding-top: 5px;"} https://twitter.com/lavaldi_
                / /controls
              / /control-group
        / /span6
        %br/
        %h3{style: "margin-left:30px;"} Datos Finales
        %br/
        .span4
          .form-horizontal
            %fieldset
              .control-group
                %label.control-label{for: "nombre", style: "width:auto;"} Red
                .controls{style: "margin-left: 90px;"}
                  %label{style: "padding-top: 5px;"} 3
                / /controls
              / /control-group
        / /span4
        .span4
          .form-horizontal
            %fieldset
              .control-group
                %label.control-label{for: "nombre", style: "width:auto;"} Lugar
                .controls{style: "margin-left: 90px;"}
                  %label{style: "padding-top: 5px;"} Mi casa
                / /controls
              / /control-group
        / /span4
        .span4
          .form-horizontal
            %fieldset
              .control-group
                %label.control-label{for: "nombre", style: "width:auto;"} Fec. Conversión
                .controls{style: "margin-left: 120px;"}
                  %label{style: "padding-top: 5px;"} 09/2013
                / /controls
              / /control-group
        / /span4
        .span6
          .form-horizontal
            %fieldset
              .control-group
                %label.control-label{for: "nombre", style: "width:auto;"} Día de Visita
                .controls{style: "margin-left: 90px;"}
                  %label{style: "padding-top: 5px;"} ----
                / /controls
              / /control-group
              .control-group
                %label.control-label{for: "nombre", style: "width:auto;"} Invitado por
                .controls{style: "margin-left: 90px;"}
                  %label{style: "padding-top: 5px;"} Nadie :(
                / /controls
              / /control-group
        / /span6
        .span6
          .form-horizontal
            %fieldset
              .control-group
                %label.control-label{for: "nombre", style: "width:auto;"} Hora
                .controls{style: "margin-left: 90px;"}
                  %label{style: "padding-top: 5px;"} -----
                / /controls
              / /control-group
              .control-group
                %label.control-label{for: "nombre", style: "width:auto;"} Motivo de Oración
                .controls{style: "margin-left: 130px;"}
                  %label{style: "padding-top: 5px;"} -----
                / /controls
              / /control-group
        / /span6